import { useState, useEffect } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
} from "@/components/ui/dialog";
import { toast } from "@/hooks/use-toast";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { Plus, Search, Eye, Trash2, Loader2 } from "lucide-react";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { bookingApi, roomApi, customerApi, rentalReceiptApi, roomTypeApi } from "@/api";

export default function Bookings() {
  const [searchTerm, setSearchTerm] = useState("");
  const [filterStatus, setFilterStatus] = useState("all");
  const [isCreateOpen, setIsCreateOpen] = useState(false);
  const [isViewDetailOpen, setIsViewDetailOpen] = useState(false);
  const [isCancelOpen, setIsCancelOpen] = useState(false);
  const [isCheckInOpen, setIsCheckInOpen] = useState(false);
  const [isCheckOutOpen, setIsCheckOutOpen] = useState(false);
  const [isApproveOpen, setIsApproveOpen] = useState(false);
  const [newGuestOpen, setNewGuestOpen] = useState(false);
  const [selectedBooking, setSelectedBooking] = useState(null);
  const [bookings, setBookings] = useState([]);
  const [isLoading, setIsLoading] = useState(false);
  const [isWalkIn, setIsWalkIn] = useState(false);
  const [walkInGuestData, setWalkInGuestData] = useState({
      HoTen: "",
      SDT: "",
      Email: "",
      CCCD: ""
  });
  const [newGuestData, setNewGuestData] = useState({
    HoTen: "",
    SDT: "",
    Email: "",
    CCCD: "",
  });
  const [formData, setFormData] = useState({
    HangPhong: "",
    NgayDen: "",
    NgayDi: "",
    SoKhach: 1,
    TienCoc: 0,
    GhiChu: "",
  });
  const [customers, setCustomers] = useState([]);
  const [rooms, setRooms] = useState([]);
  const [roomTypes, setRoomTypes] = useState([]);

  useEffect(() => {
    loadBookings();
    loadCustomers();
    loadRooms();
    loadRoomTypes();
  }, []);

  const loadBookings = async () => {
    setIsLoading(true);
    try {
      const data = await bookingApi.getBookings();
      setBookings(data);
    } catch (error) {
      toast({
        title: "Lỗi",
        description: error.message || "Không thể tải danh sách đặt phòng",
        variant: "destructive",
      });
    } finally {
      setIsLoading(false);
    }
  };

  const loadCustomers = async () => {
    try {
      const data = await customerApi.getCustomers();
      setCustomers(data);
    } catch (error) {
      console.error("Error loading customers:", error);
    }
  };

  const loadRooms = async () => {
    try {
      const data = await roomApi.getRooms();
      setRooms(data);
    } catch (error) {
      console.error("Error loading rooms:", error);
    }
  };

  const loadRoomTypes = async () => {
    try {
      const data = await roomTypeApi.getRoomTypes();
      setRoomTypes(Array.isArray(data) ? data : data.data || []);
    } catch (error) {
      console.error("Error loading room types:", error);
    }
  };

  const handleCreateBooking = async () => {
    // Validate common fields
    if (!formData.HangPhong || !formData.NgayDen || !formData.NgayDi) {
      toast({
        title: "Thiếu thông tin đặt phòng",
        description: "Vui lòng chọn hạng phòng và ngày đến/đi",
        variant: "destructive",
      });
      return;
    }

    // Validate specifics
    if (isWalkIn) {
        if (!walkInGuestData.HoTen || !walkInGuestData.CCCD) {
             toast({
                title: "Thiếu thông tin khách",
                description: "Vui lòng nhập họ tên và CCCD cho khách vãng lai",
                variant: "destructive",
              });
              return;
        }
    } else {
        if (!formData.KhachHang) {
            toast({
                title: "Thiếu khách hàng",
                description: "Vui lòng chọn khách hàng",
                variant: "destructive",
              });
              return;
        }
    }

    try {
      if (isWalkIn) {
          const payload = {
            // MaDatPhong will be auto-generated by backend
            HangPhong: formData.HangPhong,
            NgayDen: formData.NgayDen,
            NgayDi: formData.NgayDi,
            SoKhach: Number(formData.SoKhach) || 1,
            TienCoc: Number(formData.TienCoc) || 0,
            GhiChu: formData.GhiChu,
            ChiTietDatPhong: [],
            // Guest Info
            HoTen: walkInGuestData.HoTen,
            CMND: walkInGuestData.CCCD, // Backend expects CMND
            SDT: walkInGuestData.SDT,
            Email: walkInGuestData.Email
          };
          await bookingApi.createWalkInBooking(payload);
      } else {
          const payload = {
            // MaDatPhong auto-gen
            KhachHang: formData.KhachHang,
            HangPhong: formData.HangPhong,
            NgayDen: formData.NgayDen,
            NgayDi: formData.NgayDi,
            SoKhach: Number(formData.SoKhach) || 1,
            TienCoc: Number(formData.TienCoc) || 0,
            GhiChu: formData.GhiChu,
            ChiTietDatPhong: [], 
          };
          await bookingApi.createBooking(payload);
      }

      toast({
        title: "Thành công",
        description: "Đã tạo đặt phòng thành công.",
      });
      
      // Reset form
      setFormData({
        KhachHang: "",
        HangPhong: "",
        NgayDen: "",
        NgayDi: "",
        SoKhach: 1,
        TienCoc: 0,
        GhiChu: "",
      });
      setWalkInGuestData({
        HoTen: "",
        SDT: "",
        Email: "",
        CCCD: ""
      });
      setIsWalkIn(false);
      setIsCreateOpen(false);
      loadBookings();
    } catch (error) {
      toast({
        title: "Lỗi",
        description: error.message || "Không thể tạo đặt phòng",
        variant: "destructive",
      });
    }
  };

  const handleNewGuest = async () => {
    if (!newGuestData.HoTen || !newGuestData.CCCD) {
       toast({
         title: "Thiếu thông tin",
         description: "Vui lòng nhập Họ tên và CCCD/CMND",
         variant: "destructive",
       });
       return;
    }

    // Check for duplicate locally
    const existingGuest = customers.find(g => g.CMND === newGuestData.CCCD || g.Email === newGuestData.Email);
    if (existingGuest) {
       toast({
         title: "Khách hàng đã tồn tại",
         description: "Đã tìm thấy khách hàng với thông tin này. Hệ thống sẽ tự động chọn.",
       });
       setNewGuestOpen(false);
       setFormData(prev => ({ ...prev, KhachHang: existingGuest._id }));
       setNewGuestData({
        HoTen: "",
        SDT: "",
        Email: "",
        CCCD: "",
      });
       return;
    }

    try {
      const payload = {
         // MaKH will be auto-generated by backend
         HoTen: newGuestData.HoTen,
         SDT: newGuestData.SDT,
         Email: newGuestData.Email,
         CMND: newGuestData.CCCD,
      };

      const newCustomer = await customerApi.createCustomer(payload);

      toast({
        title: "Đã thêm khách hàng mới",
        description: "Thông tin khách hàng đã được lưu.",
      });
      setNewGuestOpen(false);
      setNewGuestData({ // Reset form
        HoTen: "",
        SDT: "",
        Email: "",
        CCCD: "",
      });

      // Refresh data
      await loadCustomers();

      // Auto-select the new customer in the booking form
      const customerId = newCustomer._id || newCustomer.data?._id;
      if (customerId) {
         setFormData(prev => ({ ...prev, KhachHang: customerId }));
      }
      
    } catch (error) {
      console.error("Error creating customer:", error);
       toast({
         title: "Lỗi",
         description: error.message || "Không thể tạo khách hàng",
         variant: "destructive",
       });
    }
  };

  const handleViewDetail = (booking) => {
    setSelectedBooking(booking);
    setIsViewDetailOpen(true);
  };

  const handleCancelBooking = (booking) => {
    setSelectedBooking(booking);
    setIsCancelOpen(true);
  };

  const handleConfirmCancel = async () => {
    try {
      await bookingApi.cancelBooking(selectedBooking._id);
      toast({
        title: "Đã hủy",
        description: "Đặt phòng đã được hủy thành công",
      });
      setIsCancelOpen(false);
      loadBookings();
    } catch (error) {
      toast({
        title: "Lỗi",
        description: error.message || "Không thể hủy đặt phòng",
        variant: "destructive",
      });
    }
  };

  const handleCheckIn = (booking) => {
    setSelectedBooking(booking);
    setIsCheckInOpen(true);
  };

  const handleConfirmCheckIn = async () => {
    try {
      let staffId = null;
      try {
        const staffRes = await fetch("http://localhost:5000/api/staff", {
          headers: {
            Authorization: `Bearer ${localStorage.getItem("token")}`,
          },
        });
        if (staffRes.ok) {
          const staffData = await staffRes.json();
          const staffList = Array.isArray(staffData) ? staffData : (staffData.data || []);
          if (staffList.length > 0) staffId = staffList[0]._id;
        }
      } catch (e) {
        console.warn("Could not fetch staff", e);
      }

      const updateRes = await bookingApi.updateBooking(selectedBooking._id, {
        ...selectedBooking,
        TrangThai: "CheckedIn",
      });

      const updatedBooking = updateRes.data || updateRes;

      const roomDetail = updatedBooking.ChiTietDatPhong?.[0];
      if (roomDetail && staffId) {
        const room = roomDetail.Phong;
        const roomId = typeof room === 'object' ? room._id : room;
        const roomPrice = typeof room === 'object' ? room.GiaPhong : 0;
        
        const roomTypePrices = { Normal: 400000, Standard: 600000, Premium: 900000, Luxury: 1500000 };
        const finalPrice = roomPrice || roomTypePrices[updatedBooking.HangPhong] || 0;

        await rentalReceiptApi.createRentalReceipt({
          DatPhong: updatedBooking._id,
          Phong: roomId,
          NgayNhanPhong: new Date(updatedBooking.NgayDen),
          NgayTraDuKien: new Date(updatedBooking.NgayDi),
          SoKhachThucTe: updatedBooking.SoKhach || 1,
          DonGiaSauDieuChinh: finalPrice,
          NhanVienCheckIn: staffId,
          TrangThai: "CheckedIn",
        });
      }

      toast({
        title: "Thành công",
        description: "Đã nhận phòng và khởi tạo phiếu thuê thành công",
      });
      setIsCheckInOpen(false);
      loadBookings();
    } catch (error) {
      toast({
        title: "Lỗi",
        description: error.message || "Không thể thực hiện nhận phòng",
        variant: "destructive",
      });
    }
  };

  const handleCheckOut = (booking) => {
    setSelectedBooking(booking);
    setIsCheckOutOpen(true);
  };

  const handleConfirmCheckOut = async () => {
    try {
      await bookingApi.updateBooking(selectedBooking._id, {
        ...selectedBooking,
        TrangThai: "CheckedOut",
      });
      toast({
        title: "Thành công",
        description: "Đã trả phòng thành công",
      });
      setIsCheckOutOpen(false);
      loadBookings();
    } catch (error) {
      toast({
        title: "Lỗi",
        description: error.message || "Không thể thực hiện trả phòng",
        variant: "destructive",
      });
    }
  };

  const handleApproveBooking = (booking) => {
    setSelectedBooking(booking);
    setIsApproveOpen(true);
  };

  const handleConfirmApprove = async () => {
    try {
      let staffId = null;
      try {
        const staffRes = await fetch("http://localhost:5000/api/staff", {
          headers: {
            Authorization: `Bearer ${localStorage.getItem("token")}`,
          },
        });
        if (staffRes.ok) {
          const staffData = await staffRes.json();
          const staffList = Array.isArray(staffData) ? staffData : (staffData.data || []);
          if (staffList.length > 0) staffId = staffList[0]._id;
        }
      } catch (e) {
        console.warn("Could not fetch staff", e);
      }

      const updateRes = await bookingApi.updateBooking(selectedBooking._id, {
        ...selectedBooking,
        TrangThai: "CheckedIn",
      });

      const updatedBooking = updateRes.data || updateRes;

      const roomDetail = updatedBooking.ChiTietDatPhong?.[0];
      if (roomDetail && staffId) {
        const room = roomDetail.Phong;
        const roomId = typeof room === 'object' ? room._id : room;
        const roomPrice = typeof room === 'object' ? room.GiaPhong : 0;
        
        const roomTypePrices = { Normal: 400000, Standard: 600000, Premium: 900000, Luxury: 1500000 };
        const finalPrice = roomPrice || roomTypePrices[updatedBooking.HangPhong] || 0;

        await rentalReceiptApi.createRentalReceipt({
          DatPhong: updatedBooking._id,
          Phong: roomId,
          NgayNhanPhong: new Date(updatedBooking.NgayDen),
          NgayTraDuKien: new Date(updatedBooking.NgayDi),
          SoKhachThucTe: updatedBooking.SoKhach || 1,
          DonGiaSauDieuChinh: finalPrice,
          NhanVienCheckIn: staffId,
          TrangThai: "CheckedIn",
        });
      }

      toast({
        title: "Thành công",
        description:
          "Đã phê duyệt đặt phòng và khởi tạo phiếu thuê thành công.",
      });
      setIsApproveOpen(false);
      loadBookings();
    } catch (error) {
      toast({
        title: "Lỗi",
        description: error.message || "Không thể phê duyệt đặt phòng",
        variant: "destructive",
      });
    }
  };

  const getStatusBadge = (status) => {
    const statusConfig = {
      Pending: {
        label: "Chờ xác nhận",
        className: "bg-warning text-warning-foreground",
      },
      Confirmed: {
        label: "Đã xác nhận",
        className: "bg-primary text-primary-foreground",
      },
      CheckedIn: {
        label: "Đã nhận phòng",
        className: "bg-success text-success-foreground",
      },
      CheckedOut: {
        label: "Đã trả phòng",
        className: "bg-secondary text-secondary-foreground",
      },
      Cancelled: {
        label: "Đã hủy",
        className: "bg-destructive text-destructive-foreground",
      },
    };
    const config = statusConfig[status] || {
      label: status,
      className: "bg-gray-500",
    };
    return <Badge className={config.className}>{config.label}</Badge>;
  };

  const filteredBookings = bookings.filter((booking) => {
    const matchesSearch =
      (booking.MaDatPhong &&
        booking.MaDatPhong.toLowerCase().includes(searchTerm.toLowerCase())) ||
      (booking.KhachHang &&
        booking.KhachHang.toLowerCase().includes(searchTerm.toLowerCase()));
    const matchesStatus =
      filterStatus === "all" || booking.TrangThai === filterStatus;
    return matchesSearch && matchesStatus;
  });

  return (
    <div className="space-y-6">
      <div className="flex justify-between items-center">
        <div>
          <h1 className="text-3xl font-bold text-foreground">
            Quản lý đặt phòng
          </h1>
          <p className="text-muted-foreground">
            Quản lý các đơn đặt phòng và lịch trình
          </p>
        </div>
        <Button className="gap-2" onClick={() => setIsCreateOpen(true)}>
          <Plus className="h-4 w-4" />
          Tạo đặt phòng mới
        </Button>
      </div>

      {/* Các thẻ */}
      <div className="grid gap-4 md:grid-cols-5">
        <Card>
          <CardHeader className="pb-3">
            <CardTitle className="text-sm font-medium text-muted-foreground">
              Tổng số
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{bookings.length}</div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="pb-3">
            <CardTitle className="text-sm font-medium text-muted-foreground">
              Chờ xác nhận
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">
              {bookings.filter((b) => b.TrangThai === "Pending").length}
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="pb-3">
            <CardTitle className="text-sm font-medium text-muted-foreground">
              Đã xác nhận
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">
              {bookings.filter((b) => b.TrangThai === "Confirmed").length}
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="pb-3">
            <CardTitle className="text-sm font-medium text-muted-foreground">
              Đã nhận phòng
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">
              {bookings.filter((b) => b.TrangThai === "CheckedIn").length}
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="pb-3">
            <CardTitle className="text-sm font-medium text-muted-foreground">
              Đã trả phòng
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">
              {bookings.filter((b) => b.TrangThai === "CheckedOut").length}
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Filters */}
      <Card>
        <CardContent className="pt-6">
          <div className="flex gap-4">
            <div className="flex-1 relative">
              <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 h-4 w-4 text-muted-foreground" />
              <Input
                placeholder="Tìm kiếm theo mã đặt phòng, tên khách..."
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
                className="pl-9"
              />
            </div>
            <Select value={filterStatus} onValueChange={setFilterStatus}>
              <SelectTrigger className="w-[180px]">
                <SelectValue placeholder="Trạng thái" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="all">Tất cả trạng thái</SelectItem>
                <SelectItem value="Pending">Chờ xác nhận</SelectItem>
                <SelectItem value="Confirmed">Đã xác nhận</SelectItem>
                <SelectItem value="CheckedIn">Đã nhận phòng</SelectItem>
                <SelectItem value="CheckedOut">Đã trả phòng</SelectItem>
                <SelectItem value="Cancelled">Đã hủy</SelectItem>
              </SelectContent>
            </Select>
          </div>
        </CardContent>
      </Card>

      {/* Bảng đặt phòng*/}
      <Card>
        <CardHeader>
          <CardTitle>Danh sách đặt phòng ({filteredBookings.length})</CardTitle>
        </CardHeader>
        <CardContent>
          {isLoading ? (
            <div className="flex items-center justify-center py-8">
              <Loader2 className="h-6 w-6 animate-spin" />
            </div>
          ) : (
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Mã đặt phòng</TableHead>
                  <TableHead>Hạng phòng</TableHead>
                  <TableHead>Nhận phòng</TableHead>
                  <TableHead>Trả phòng</TableHead>
                  <TableHead>Số khách</TableHead>
                  <TableHead>Tiền cọc</TableHead>
                  <TableHead>Trạng thái</TableHead>
                  <TableHead className="text-right">Thao tác</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {filteredBookings.map((booking) => (
                  <TableRow key={booking._id}>
                    <TableCell className="font-medium">
                      {booking.MaDatPhong}
                    </TableCell>
                    <TableCell>{booking.HangPhong}</TableCell>
                    <TableCell>
                      {booking.NgayDen
                        ? new Date(booking.NgayDen).toLocaleDateString("vi-VN")
                        : "N/A"}
                    </TableCell>
                    <TableCell>
                      {booking.NgayDi
                        ? new Date(booking.NgayDi).toLocaleDateString("vi-VN")
                        : "N/A"}
                    </TableCell>
                    <TableCell>{booking.SoKhach}</TableCell>
                    <TableCell>
                      {booking.TienCoc?.toLocaleString("vi-VN") || "0"} VNĐ
                    </TableCell>
                    <TableCell>{getStatusBadge(booking.TrangThai)}</TableCell>
                    <TableCell className="text-right">
                      <div className="flex justify-end gap-2">
                        <Button
                          variant="ghost"
                          size="icon"
                          onClick={() => handleViewDetail(booking)}
                        >
                          <Eye className="h-4 w-4" />
                        </Button>
                        {booking.TrangThai === "Pending" && (
                          <Button
                            variant="default"
                            size="sm"
                            onClick={() => handleApproveBooking(booking)}
                          >
                            Phê duyệt
                          </Button>
                        )}
                        {booking.TrangThai === "Confirmed" && (
                          <Button
                            variant="ghost"
                            size="sm"
                            onClick={() => handleCheckIn(booking)}
                          >
                            Check-in
                          </Button>
                        )}
                        {booking.TrangThai === "CheckedIn" && (
                          <Button
                            variant="ghost"
                            size="sm"
                            onClick={() => handleCheckOut(booking)}
                          >
                            Check-out
                          </Button>
                        )}
                        {booking.TrangThai !== "Cancelled" &&
                          booking.TrangThai !== "CheckedOut" && (
                            <Button
                              variant="ghost"
                              size="icon"
                              onClick={() => handleCancelBooking(booking)}
                            >
                              <Trash2 className="h-4 w-4" />
                            </Button>
                          )}
                      </div>
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          )}
        </CardContent>
      </Card>

      <Dialog open={isCreateOpen} onOpenChange={setIsCreateOpen}>
        <DialogContent className="sm:max-w-[600px]">
          <DialogHeader>
            <DialogTitle>Đặt phòng mới</DialogTitle>
            <DialogDescription>
              Điền thông tin đặt phòng cho khách hàng
            </DialogDescription>
          </DialogHeader>
          
          <div className="grid gap-4 py-4">

            {/* Guest Selection / Entry */}
            {isWalkIn ? (
                <div className="grid grid-cols-2 gap-4">
                    <div className="grid gap-2">
                        <Label htmlFor="guestName">Họ tên *</Label>
                        <Input
                            id="guestName"
                            value={walkInGuestData.HoTen}
                            onChange={(e) => setWalkInGuestData({...walkInGuestData, HoTen: e.target.value})}
                            placeholder="Nguyễn Văn A"
                        />
                    </div>
                    <div className="grid gap-2">
                        <Label htmlFor="guestCCCD">CCCD/CMND *</Label>
                        <Input
                            id="guestCCCD"
                            value={walkInGuestData.CCCD}
                            onChange={(e) => setWalkInGuestData({...walkInGuestData, CCCD: e.target.value})}
                            placeholder="0123456789"
                        />
                    </div>
                     <div className="grid gap-2">
                        <Label htmlFor="guestPhone">Số điện thoại</Label>
                        <Input
                            id="guestPhone"
                            value={walkInGuestData.SDT}
                            onChange={(e) => setWalkInGuestData({...walkInGuestData, SDT: e.target.value})}
                            placeholder="0987654321"
                        />
                    </div>
                    <div className="grid gap-2">
                        <Label htmlFor="guestEmail">Email</Label>
                        <Input
                            id="guestEmail"
                            value={walkInGuestData.Email}
                            onChange={(e) => setWalkInGuestData({...walkInGuestData, Email: e.target.value})}
                            placeholder="example@mail.com"
                        />
                    </div>
                </div>
            ) : (
                <div className="grid gap-2">
                    <Label>Khách hàng</Label>
                    <div className="flex gap-2">
                    <Select
                        value={formData.KhachHang}
                        onValueChange={(value) =>
                        setFormData({ ...formData, KhachHang: value })
                        }
                    >
                    <SelectTrigger className="w-full">
                        <SelectValue placeholder="Chọn khách hàng" />
                    </SelectTrigger>
                    <SelectContent>
                        {customers.map((guest) => (
                        <SelectItem key={guest._id} value={guest._id}>
                            {guest.HoTen}{guest.CCCD ? ` - ${guest.CCCD}` : ''}
                        </SelectItem>
                        ))}
                    </SelectContent>
                    </Select>
                    <Button
                    variant="outline"
                    size="icon"
                    onClick={() => setNewGuestOpen(true)}
                    >
                    <Plus className="h-4 w-4" />
                    </Button>
                    </div>
                </div>
            )}

            <div className="grid gap-2">
              <Label>Loại phòng</Label>
              <Select
                value={formData.HangPhong}
                onValueChange={(value) =>
                  setFormData({ ...formData, HangPhong: value })
                }
              >
                <SelectTrigger>
                  <SelectValue placeholder="Chọn loại phòng" />
                </SelectTrigger>
                <SelectContent>
                   {roomTypes.map((type) => (
                      <SelectItem key={type._id} value={type.TenLoaiPhong}>
                        {type.TenLoaiPhong}
                      </SelectItem>
                   ))}
                </SelectContent>
              </Select>
            </div>

            <div className="grid grid-cols-2 gap-4">
              <div className="grid gap-2">
                <Label htmlFor="check-in">Ngày nhận phòng</Label>
                <Input
                  id="check-in"
                  type="date"
                  value={formData.NgayDen}
                  onChange={(e) =>
                    setFormData({ ...formData, NgayDen: e.target.value })
                  }
                />
              </div>
              <div className="grid gap-2">
                <Label htmlFor="check-out">Ngày trả phòng</Label>
                <Input
                  id="check-out"
                  type="date"
                  value={formData.NgayDi}
                  onChange={(e) =>
                    setFormData({ ...formData, NgayDi: e.target.value })
                  }
                />
              </div>
            </div>

            <div className="grid grid-cols-2 gap-4">
                 <div className="grid gap-2">
                    <Label htmlFor="deposit">Tiền cọc (VNĐ)</Label>
                    <Input
                        id="deposit"
                        type="number"
                        min="0"
                        value={formData.TienCoc}
                        onChange={(e) => setFormData({ ...formData, TienCoc: e.target.value })}
                    />
                </div>
            </div>

             <div className="grid gap-2">
                <Label htmlFor="note">Ghi chú</Label>
                <Textarea
                    id="note"
                    placeholder="Ghi chú đặc biệt..."
                    value={formData.GhiChu}
                    onChange={(e) => setFormData({ ...formData, GhiChu: e.target.value })}
                />
            </div>

          </div>
          <DialogFooter>
            <Button
              variant="outline"
              onClick={() => setIsCreateOpen(false)}
            >
              Hủy
            </Button>
            <Button onClick={handleCreateBooking}>Xác nhận</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
      
      {/* New Guest Dialog */}
      <Dialog open={newGuestOpen} onOpenChange={setNewGuestOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Thêm khách hàng mới</DialogTitle>
          </DialogHeader>
          <div className="grid gap-4 py-4">
             <div className="grid gap-2">
              <Label>Họ tên *</Label>
              <Input
                value={newGuestData.HoTen}
                onChange={(e) => setNewGuestData({...newGuestData, HoTen: e.target.value})}
              />
            </div>
            <div className="grid gap-2">
              <Label>CCCD/CMND *</Label>
              <Input
                value={newGuestData.CCCD}
                onChange={(e) => setNewGuestData({...newGuestData, CCCD: e.target.value})}
              />
            </div>
            <div className="grid gap-2">
              <Label>Số điện thoại</Label>
              <Input
                value={newGuestData.SDT}
                onChange={(e) => setNewGuestData({...newGuestData, SDT: e.target.value})}
              />
            </div>
             <div className="grid gap-2">
              <Label>Email</Label>
              <Input
                value={newGuestData.Email}
                onChange={(e) => setNewGuestData({...newGuestData, Email: e.target.value})}
              />
            </div>
          </div>
          <DialogFooter>
             <Button variant="outline" onClick={() => setNewGuestOpen(false)}>Hủy</Button>
             <Button onClick={handleNewGuest}>Thêm mới</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* PopUp chi tiết đặt phòng */}
      <Dialog open={isViewDetailOpen} onOpenChange={setIsViewDetailOpen}>
        <DialogContent className="sm:max-w-[600px]">
          <DialogHeader>
            <DialogTitle>Chi tiết đặt phòng</DialogTitle>
          </DialogHeader>
          {selectedBooking && (
            <div className="grid gap-4 py-4">
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <Label className="text-muted-foreground">Mã đặt phòng</Label>
                  <p className="text-lg font-semibold">
                    {selectedBooking.MaDatPhong}
                  </p>
                </div>
                <div>
                  <Label className="text-muted-foreground">Trạng thái</Label>
                  <div className="mt-1">
                    {getStatusBadge(selectedBooking.TrangThai)}
                  </div>
                </div>
                <div>
                  <Label className="text-muted-foreground">Hạng phòng</Label>
                  <p className="text-lg font-semibold">
                    {selectedBooking.HangPhong}
                  </p>
                </div>
                <div>
                  <Label className="text-muted-foreground">Số khách</Label>
                  <p className="text-lg font-semibold">
                    {selectedBooking.SoKhach} người
                  </p>
                </div>
                <div>
                  <Label className="text-muted-foreground">Ngày nhận</Label>
                  <p className="text-lg font-semibold">
                    {selectedBooking.NgayDen
                      ? new Date(selectedBooking.NgayDen).toLocaleDateString(
                          "vi-VN"
                        )
                      : "N/A"}
                  </p>
                </div>
                <div>
                  <Label className="text-muted-foreground">Ngày trả</Label>
                  <p className="text-lg font-semibold">
                    {selectedBooking.NgayDi
                      ? new Date(selectedBooking.NgayDi).toLocaleDateString(
                          "vi-VN"
                        )
                      : "N/A"}
                  </p>
                </div>
                <div>
                  <Label className="text-muted-foreground">Tiền cọc</Label>
                  <p className="text-lg font-semibold">
                    {selectedBooking.TienCoc?.toLocaleString("vi-VN") || "0"}{" "}
                    VNĐ
                  </p>
                </div>
              </div>
              {selectedBooking.GhiChu && (
                <div>
                  <Label className="text-muted-foreground">Ghi chú</Label>
                  <p className="mt-1">{selectedBooking.GhiChu}</p>
                </div>
              )}
            </div>
          )}
          <DialogFooter>
            <Button onClick={() => setIsViewDetailOpen(false)}>Đóng</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* PopUp hủy đặt phòng */}
      <Dialog open={isCancelOpen} onOpenChange={setIsCancelOpen}>
        <DialogContent className="sm:max-w-[400px]">
          <DialogHeader>
            <DialogTitle>Hủy đặt phòng</DialogTitle>
          </DialogHeader>
          {selectedBooking && (
            <div className="py-4">
              <p>
                Bạn có chắc chắn muốn hủy đặt phòng{" "}
                <strong>{selectedBooking.MaDatPhong}</strong>?
              </p>
            </div>
          )}
          <DialogFooter>
            <Button variant="outline" onClick={() => setIsCancelOpen(false)}>
              Không
            </Button>
            <Button variant="destructive" onClick={handleConfirmCancel}>
              Xác nhận hủy
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* PopUp checkin */}
      <Dialog open={isCheckInOpen} onOpenChange={setIsCheckInOpen}>
        <DialogContent className="sm:max-w-[400px]">
          <DialogHeader>
            <DialogTitle>Nhận phòng (Check-in)</DialogTitle>
          </DialogHeader>
          {selectedBooking && (
            <div className="grid gap-4 py-4">
              <div>
                <Label className="text-muted-foreground">Mã đặt phòng</Label>
                <p className="text-lg font-semibold">
                  {selectedBooking.MaDatPhong}
                </p>
              </div>
              <div>
                <Label className="text-muted-foreground">Hạng phòng</Label>
                <p className="text-lg font-semibold">
                  {selectedBooking.HangPhong}
                </p>
              </div>
              <div>
                <Label className="text-muted-foreground">Số khách</Label>
                <p className="text-lg font-semibold">
                  {selectedBooking.SoKhach} người
                </p>
              </div>
            </div>
          )}
          <DialogFooter>
            <Button variant="outline" onClick={() => setIsCheckInOpen(false)}>
              Hủy
            </Button>
            <Button onClick={handleConfirmCheckIn}>Xác nhận check-in</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* PopUp checkout */}
      <Dialog open={isCheckOutOpen} onOpenChange={setIsCheckOutOpen}>
        <DialogContent className="sm:max-w-[400px]">
          <DialogHeader>
            <DialogTitle>Trả phòng (Check-out)</DialogTitle>
          </DialogHeader>
          {selectedBooking && (
            <div className="grid gap-4 py-4">
              <div>
                <Label className="text-muted-foreground">Mã đặt phòng</Label>
                <p className="text-lg font-semibold">
                  {selectedBooking.MaDatPhong}
                </p>
              </div>
              <div>
                <Label className="text-muted-foreground">Hạng phòng</Label>
                <p className="text-lg font-semibold">
                  {selectedBooking.HangPhong}
                </p>
              </div>
              <div>
                <Label className="text-muted-foreground">Số khách</Label>
                <p className="text-lg font-semibold">
                  {selectedBooking.SoKhach} người
                </p>
              </div>
              <p className="text-sm text-muted-foreground">
                Hệ thống sẽ tự động tạo hóa đơn sau khi check-out.
              </p>
            </div>
          )}
          <DialogFooter>
            <Button variant="outline" onClick={() => setIsCheckOutOpen(false)}>
              Hủy
            </Button>
            <Button onClick={handleConfirmCheckOut}>Xác nhận check-out</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* PopUp phê duyệt đặt phòng */}
      <Dialog open={isApproveOpen} onOpenChange={setIsApproveOpen}>
        <DialogContent className="sm:max-w-[400px]">
          <DialogHeader>
            <DialogTitle>Phê duyệt đặt phòng</DialogTitle>
          </DialogHeader>
          {selectedBooking && (
            <div className="py-4">
              <p className="mb-4">
                Bạn có chắc chắn muốn phê duyệt đặt phòng{" "}
                <strong>{selectedBooking.MaDatPhong}</strong>?
              </p>
              <div className="grid gap-4">
                <div>
                  <Label className="text-muted-foreground">Mã đặt phòng</Label>
                  <p className="text-lg font-semibold">
                    {selectedBooking.MaDatPhong}
                  </p>
                </div>
                <div>
                  <Label className="text-muted-foreground">Hạng phòng</Label>
                  <p className="text-lg font-semibold">
                    {selectedBooking.HangPhong}
                  </p>
                </div>
                <div>
                  <Label className="text-muted-foreground">Khách hàng</Label>
                  <p className="text-lg font-semibold">
                    {typeof selectedBooking.KhachHang === "object"
                      ? selectedBooking.KhachHang?.HoTen ||
                        selectedBooking.KhachHang?.TenKhach ||
                        "N/A"
                      : selectedBooking.KhachHang}
                  </p>
                </div>
                <p className="text-sm text-muted-foreground pt-2 border-t">
                  Sau khi phê duyệt, khách hàng có thể sử dụng các dịch vụ của
                  khách sạn.
                </p>
              </div>
            </div>
          )}
          <DialogFooter>
            <Button variant="outline" onClick={() => setIsApproveOpen(false)}>
              Hủy
            </Button>
            <Button onClick={handleConfirmApprove}>Xác nhận phê duyệt</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}
